# Prettier 配置文件

# 每行字符数不限制
printWidth: 9007199254740991
# 缩进使用的空格数
tabWidth: 2
# 是否使用 tab 缩进，false 表示使用空格
useTabs: false
# 是否在语句末尾添加分号
semi: true
# 是否使用单引号，false 表示使用双引号
singleQuote: false
# 对象属性名加引号的方式："as-needed"仅在必要时添加
quoteProps: "as-needed"
# JSX 中是否使用单引号，false 表示使用双引号
jsxSingleQuote: false
# 多行结构中尾后逗号的处理方式，"es5"表示在 ES5 中有效的地方添加
trailingComma: "es5"
# 对象字面量中括号之间是否添加空格
bracketSpacing: true
# 多行 HTML 元素的结束标签是否与最后一个属性在同一行
bracketSameLine: false
# 箭头函数参数周围是否使用括号，"avoid" 表示在可以省略的情况下不使用括号
arrowParens: "avoid"
# 行尾换行符，"lf"表示仅使用换行符
endOfLine: "lf"
# 是否格式化嵌入的代码块，"auto"表示自动检测
embeddedLanguageFormatting: "auto"
# 是否将 JSX/HTML 的每个属性放在单独的行上，false 表示不强制每个属性一行
singleAttributePerLine: false
# 使用的插件
plugins:
  - "prettier-plugin-astro"
# 特定文件类型的覆盖配置
overrides:
  # Markdown 文件的配置
  - files: "*.md"
    options:
      # 保留原始文本换行
      proseWrap: "preserve"
  # MDX 文件的配置
  - files: "*.mdx"
    options:
      # 保留原始文本换行
      proseWrap: "preserve"
  # Astro 文件的配置
  - files: "*.astro"
    options:
      # 使用 astro 解析器
      parser: "astro"
